# -*- coding: utf-8 -*-
"""HuggingFace.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QdaN-HbrEHDu4cdA0YnS69-L3yyfM5kS
"""

!nvidia-smi

"""# 1 TEXT GENERATION MODEL (MODEL-GPT2) (NLP)"""

from transformers import pipeline

generator = pipeline("text-generation", model= 'gpt2')
response = generator('what is Hugging Face', max_length = 40, num_return_sequences=1)
print(response[0]['generated_text'])

"""# 2 NER (NAMED ENTITY RECOGNITION)(N(NLP)"""

from transformers import pipeline

ner = pipeline("ner", aggregation_strategy="simple")

entities = ner("My name is pallavi khadse")
print(entities)

"""# 3- SENTIMENT ANALYSIS"""

# installed librabry# !pip install transformers datasets

from transformers import pipeline

classifier = pipeline('sentiment-analysis')
result = classifier('I love Hugging face library very much, it is so nice')
print(result)

from transformers import pipeline

classifier = pipeline('sentiment-analysis')
result = classifier('The food is not tasty')
print(result)

"""# Fronted Part"""

!pip install gradio

import gradio as gr

from transformers import pipeline

classifier = pipeline('sentiment-analysis')

def analyze_sentiment(text):
  return classifier(text)[0]['label']

gr.Interface(fn = analyze_sentiment, inputs= 'text', outputs='text').launch()

"""# 4 TEXT TO IMAGE MODEL USING DIFFUSION PIPELINE"""

from diffusers import StableDiffusionPipeline
import torch

model_id = "sd-legacy/stable-diffusion-v1-5"
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16)
pipe = pipe.to("cuda")

prompt = "beautiful girl walking in street light with her pet dog"
image = pipe(prompt).images[0]

image.save("beautiful girl.png")

import gradio as gr
from diffusers import StableDiffusionPipeline
import torch
import os

model_id = "sd-legacy/stable-diffusion-v1-5"

pipe = StableDiffusionPipeline.from_pretrained(
    model_id,
    torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32
)

device = "cuda" if torch.cuda.is_available() else "cpu"
pipe = pipe.to(device)

# create folder
os.makedirs("outputs", exist_ok=True)

def generated_image(prompt):
    image = pipe(prompt).images[0]
    image.save(f"outputs/{prompt[:20]}.png")  # limit filename
    return image

# UI
gr.Interface(
    fn=generated_image,
    inputs=gr.Textbox(label='Enter your prompt', placeholder='beautiful girl walking in street with dog'),
    outputs=gr.Image(type='pil', label='Generated Image'),
    title='Pallavi Khadse Text - Image Generator',
    description='Enter your prompt and see your generated image'
).launch()